import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Open_Sans} from "next/font/google";
import './globals.css'

import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/provider/theme-provider';
import { ModalProvider } from '@/components/provider/modal-provider';

const font = Open_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: 'Discord application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.variable , "antialiased" , "bg-white dark:bg-[#38393a]")}>
          
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <h2 className='text-3xl text-blue-700 text-left'>Discord</h2>
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-ceramic-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>

        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        // forcedTheme='dark'
        enableSystem
        disableTransitionOnChange
       >

       {/* <ModalProvider /> */}

            {/* // {children}
            // </ModalProvider>  */}
     {children}

        </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}


// suppressHydrationWarning:  “React, please ignore the mismatch warnings inside this component / element. I know they will be different. Don't show hydration error.”